# NumPy : Numerical Python
is a popular Python library used for working with numbers, arrays, matrices, and scientific computing.

# Why use NumPy?

NumPy is much faster and more efficient than using regular Python lists for numerical calculations. It provides powerful tools for:

- Multi-dimensional arrays
- Mathematical operations
- Linear algebra
- Statistics
- Random number generation
- Data analysis and machine learning

## array can be converted from: tuple, list,set,dict

## First, install it if needed:

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


# Import NumPy:

In [4]:
import numpy as np

# What is a NumPy Array?

A NumPy array is a collection of elements of the same data type stored in a contiguous block of memory. It is similar to a Python list but is faster, more memory-efficient, and supports mathematical operations directly.

## How to Create a NumPy Array
- 1. Using np.array()

In [12]:
# 1D array
arr = np.array([1,3,4,5])
print(arr)
print(type(arr)) 
print(arr.dtype)# ndarray = n dimendional array

[1 3 4 5]
<class 'numpy.ndarray'>
int64


### 2D array

In [16]:
arr_2D = np.array([[1,2,3],
                  [3,4,5.5]])
print(arr_2D)
print(type(arr_2D)) 

[[1.  2.  3. ]
 [3.  4.  5.5]]
<class 'numpy.ndarray'>


Although you provided both integers (1, 2, 3, 4) and a float (5.5), NumPy arrays must have one common data type.

So NumPy automatically upcasts all integers to floats:

In [11]:
print(arr_2D.dtype)

float64


### 3D array

In [21]:
arr_3D = np.array([[[1,2,3],
                  [3,4,5]],
                  
                  [[5,6,7],
                  [7,8,9]]])
print(arr_3D)       

[[[1 2 3]
  [3 4 5]]

 [[5 6 7]
  [7 8 9]]]


- 1D = Row of values
- 2D = Table (rows and columns)
- 3D = Collection of tables (multiple sheets)

# using built-in functions

# crerate 3 x 3 array filed with zeros

In [23]:
zeros_arr = np.zeros([3,3])
print(zeros_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [24]:
zeros_arr = np.zeros((2,3))
print(zeros_arr)

[[0. 0. 0.]
 [0. 0. 0.]]


## create array filled with ones

In [28]:
ones_arr = np.ones([2,2])
print(ones_arr)

[[1. 1.]
 [1. 1.]]


## arange() : is used to create an array of numbers within a specified range.
np.arange(start, stop, step)

by default it created 1D array

In [29]:
arr = np.arange(5)
print(arr)

[0 1 2 3 4]


In [30]:
arr = np.arange(1,5,2)
print(arr)

[1 3]


In [35]:
arr = np.arange(10,1,-1)
print(arr)

[10  9  8  7  6  5  4  3  2]


### np.arange() creates a 1D array by default. To make it 2D, use .reshape().

In [39]:
arr = np.arange(1,7).reshape(2,3)
print(arr)

[[1 2 3]
 [4 5 6]]


## linspace() : is used to create equally spaced numbers between a start and stop value.

Syntax
- np.linspace(start, stop, num)

In [49]:
lin_arr = np.linspace(1,10,4)
print(lin_arr)

[ 1.  4.  7. 10.]


In [46]:
lin_arr = np.linspace(1,10,8).reshape(2,4)
print(lin_arr)

[[ 1.          2.28571429  3.57142857  4.85714286]
 [ 6.14285714  7.42857143  8.71428571 10.        ]]


## Random array : 1. np.random.rand()  : Generates random decimal numbers between 0 and 1.

In [51]:
random_arr = np.random.rand(3,3)
print(random_arr)

[[0.04731121 0.2492326  0.39864978]
 [0.22507733 0.92845148 0.42121339]
 [0.84670974 0.37671331 0.92592994]]


## 2. np.random.randint() : Generates random integers within a range.

In [57]:
rand_arr = np.random.randint(1,10,11)
print(rand_arr)

[1 6 4 3 2 6 7 9 5 7 6]


### 4. Create a 2D Random Array

In [58]:
rand_2D = np.random.randint(1,10,(3,4))
print(rand_2D)

[[4 2 7 3]
 [6 9 3 8]
 [7 2 7 5]]


## ndim : stands for Number of Dimensions(1D,2D etc.)

In [60]:
arr = np.array([1,2,3,4])
print(arr)
print(arr.ndim)

[1 2 3 4]
1


In [62]:
arr = np.array([[1,2,3,4],[2,3,4,5]])
print(arr)
print(arr.ndim)

[[1 2 3 4]
 [2 3 4 5]]
2


## using dimension to create N-dimension array

In [65]:
arr = np.array([1,2,3,4], ndmin=4)
print(arr)

[[[[1 2 3 4]]]]


### ndim = "Dimension?" → Ask the array how many dimensions it has.
### ndmin = "Minimum Dimensions" → Tell NumPy how many dimensions you want at minimum.

# shape : tells you the size of an array in each dimension.


In [69]:
arr = np.array([1,2])
print(arr)
print(arr.shape) 
    #Meaning: 4 elements

[1 2]
(2,)


In [71]:
arr = np.array([[1,2],[1,2]])
print(arr)
print(arr.shape) 
#Meaning: 2 rows 2 columns

[[1 2]
 [1 2]]
(2, 2)


In [72]:
arr = np.array([
    [[1, 2, 3],
     [4, 5, 6]],

    [[7, 8, 9],
     [10, 11, 12]]
])

print(arr.shape)

(2, 2, 3)


In [74]:
'''Meaning:

2 blocks (tables)
2 rows in each block
3 columns in each row'''

'Meaning:\n\n2 blocks (tables)\n2 rows in each block\n3 columns in each row'

## reshape(): is used to change the shape of an array without changing its data.

arr.reshape(rows, columns)


In [76]:
arr = np.array([1,2,3,4])
new_arr = arr.reshape(2,2)
print(new_arr)

[[1 2]
 [3 4]]


# data types in Numpy

### strings are sequence of characters such as letters, numbers, symbols or spaces enclosed within single quotes(') or double quote(")

we can mention a data type


In [81]:
arr = np.array(['a','b','c'],dtype=np.str_)
print(arr)
print(arr.dtype)
print(type(arr))

['a' 'b' 'c']
<U1
<class 'numpy.ndarray'>


### integers are whole numbers +ve or -ve without decimal points

In [87]:
arr = np.array([1,2,3,4,5],dtype=np.int64)
print("int:",arr)

int: [1 2 3 4 5]


In [85]:
# float
arr = np.array([1,2,3,4,5],dtype=np.float64)
print("float:",arr)

float: [1. 2. 3. 4. 5.]


In [89]:
# boolean
arr = np.array([True, True, False],dtype=np.bool_)
print("float:",arr)

float: [ True  True False]


In [90]:
# complex data types
arr = np.array([1+2j],dtype=np.complex128)
print("float:",arr)

float: [1.+2.j]


## type(arr)
- Tells you what kind of object arr is.
- <class 'numpy.ndarray'> : -  arr is a NumPy array object (ndarray = N-dimensional array).

## arr.dtype
- Tells you the data type of the elements stored inside the array.
   -  int64 : All elements inside the array are integers of type int64.

## creating numpy array with specific data type using dtype parameter

### creating array of integer without specifying the data type

In [91]:
arr = np.array([1,2,3])
print(arr.dtype)

int64


In [101]:
arr = np.array(['asha', 'biradar'], dtype = 'S2')
print(arr.dtype)
print(arr)

|S2
[b'as' b'bi']


What does dtype='S1' mean?

S = String (bytes string)

1 = Store only 1 character for each element

So NumPy allocates space for only 1 byte/character per element

'asha' → 'a'

'biradar' → 'b'

The b indicates a bytes string.

# Indexing and Slicing in Numpy Array
Indexing is used to access a specific element using its position.

Slicing is used to access a range of elements using:

In [103]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [106]:
# Indexing
element = arr[0,1]  # accesing the element at first row and 2nd column 
print(element)

2


### slicing row

In [108]:
slice_row = arr[1,:]  # select 1st row and all columns
print(slice_row)

[4 5 6]


In [110]:
slice_row = arr[1:]  # Start from row index 1 and go till the end.
print(slice_row)

[[4 5 6]
 [7 8 9]]


In [111]:
slice_column = arr[:,2]  # select all rows and 2nd column
print(slice_column)

[3 6 9]


In [115]:
slice_column = arr[:2]  # Start from 0 and stop before 2
print(slice_column)

[[1 2 3]
 [4 5 6]]


### Advanced Indexing with boolean masking
Boolean masking means selecting elements from an array using True and False conditions.

In [116]:
# create a array
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [117]:
# apply condition
mask = arr > 5
print(mask)

[[False False False]
 [False False  True]
 [ True  True  True]]


In [120]:
# use the mask
print(arr[mask])
# NumPy returns only the values where the mask is True.

[6 7 8 9]


In [122]:
## Short Form
#Instead of creating mask separately:
print(arr[arr >5])

[6 7 8 9]


In [5]:
# updating value in numpy array
arr = np.array(['apple', 'banana'])
arr[arr=='banana'] = 'cherry'
print(arr)

['apple' 'cherry']


### Where(): The numpy.where() function is used to find elements based on a condition. It can:

Return the indices where a condition is True.
    
Replace values based on a condition.
    
    ** Syntax **
- numpy.where(condition, x, y)
- condition → Boolean condition.
- x → Value if condition is True.
- y → Value if condition is False.

In [6]:
arr = np.array([10,20,30,40,50])
new_arr = np.where(arr>30, "High", "low")
print(new_arr)

['low' 'low' 'low' 'High' 'High']


In [8]:
# Find Indices
new_arr = np.where(arr>30)
print(new_arr)
# Elements greater than 30 are at index positions 3 and 4.

(array([3, 4]),)


In [11]:
# Multiple Conditions
new_arr = np.where((arr>20) & (arr<50),'valid', 'invalid')
print(new_arr)

['invalid' 'invalid' 'valid' 'valid' 'invalid']


# sum() : The np.sum() function is used to calculate the sum of array elements.

- Syntax
- np.sum(array, axis=None)
- array → Input array.
- axis=None → Sum of all elements (default).
- axis=0 → Sum column-wise.
- axis=1 → Sum row-wise.

In [13]:
print(np.sum(arr>30))

2


In [14]:
# Sum of All Elements
sum_arr = np.array([10,20,30])
print(np.sum(sum_arr>=10))    # counts element

3


In [16]:
result = np.sum(sum_arr)    # sums element
print(result)

60


In [18]:
result = arr.sum()
print(result)

150


#### Both np.sum(arr) and arr.sum() give the same result.

In [19]:
# Column-wise Sum (axis=0)

arr = np.array([[1, 2, 3],
                [4, 5, 6]])
result = np.sum(arr,axis=0)
print(result)

[5 7 9]


In [21]:
# row-wise Sum (axis=1)
result = np.sum(arr,axis=1)
print(result)

[ 6 15]


## Slicing 

In [23]:
a = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]]
            )
b= a[:2, 1:3]
b

array([[2, 3],
       [6, 7]])

In [24]:
c= a[1:, 2:]
c

array([[ 7,  8],
       [11, 12]])

# Numpy Operations

#### Numpy array support wide range of operations : including, statistical, arithmatic,Comparison, Logical, Aggregate, Trigonometric, Exponential and Logarithmic Operations, Bitwise 9. Matrix Operations etc.
#### these operations are performed elemnt-wise
# ### 


### Element wise Arithmetic Operations:
Element-wise arithmetic operations mean that NumPy performs the operation on corresponding elements of arrays.

In [35]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])


#### element wise Addition : added by index

In [36]:
addition = arr1 + arr2
print(addition)
# 1+4 2+5 3+6

[5 7 9]


In [37]:
# elemnt wise sunstraction
substraction = arr2 - arr1
print(substraction)

[3 3 3]


In [151]:
# elemnt wise Multiplication
multiplication = arr1 * arr2
print(multiplication)

[ 0.          7.85398163 18.84955592]


In [39]:
# elemnt wise Division
division = arr1 / arr2
print(division)

[0.25 0.4  0.5 ]


# Statistical Operations

In [41]:
# learnmean , variance, standard deviation
# why it it needed, what is use of it, what ids difference between them , where do we use, how we use, how formula created
# learn degrees of fredom


### Statistical operations are functions used to analyze data and calculate statistical measures such as average, median, variance, standard deviation, minimum, maximum, etc.

### These operations help summarize and understand the characteristics of data.

## 1. Mean (Average) : The mean is the sum of all values divided by the number of values.
 ## Formula:   Mean= (∑x) / n

In [48]:
arr = np.array([1,2,3,4,5])
print("mean of array: ", np.mean(arr))
print("standard deviation: ", np.std(arr))

mean of array:  3.0
standard deviation:  1.4142135623730951


## 2. Median : The median is the middle value after sorting the data.

In [51]:
print(np.median(arr))

3.0


## 3. Standard Deviation (std) : Standard deviation measures how spread out the data is from the mean.
- Small std → values are close to the mean.
- Large std → values are spread out.

## 4. Variance (var) :Variance is the square of the standard deviation.

In [52]:
print(np.var(arr))

2.0


# Geometric Operations
Geometric operations in NumPy are operations related to shapes, distances, angles, vectors, and matrix transformations. They are commonly used in computer graphics, machine learning, robotics, image processing, and data science.

### Exponential () = np.exp()
### Raises each element of the array to the power of euler's number(e)

In [54]:
arr = np.array([1,2,3,4,5])
print(np.exp(arr))

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


### Square root : computes square root of each elemnt

In [55]:
arr1 = np.array([4,16])
print(np.sqrt(arr1))

[2. 4.]


## sine = computes the sine of each elemnt in array treated as angles in radians

In [56]:
np.pi

3.141592653589793

In [59]:
arr1 = np.array([0, np.pi/2, np.pi])
print(np.sin(arr1))


[0.0000000e+00 1.0000000e+00 1.2246468e-16]


## cos

In [60]:
print(np.cos(arr1))

[ 1.000000e+00  6.123234e-17 -1.000000e+00]


In [61]:
print(np.tan(arr1))

[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


## Natural Logarithm : computes the natural logarithm (base e) of each element of array

In [66]:
arr = np.array([1,2,3])
print(np.log(arr))
# why log needed

[0.         0.69314718 1.09861229]


## Aggreagtes functions

### sum : computes sum of all elemnts in an array

In [68]:
arr = np.array([1,2,3])
print(np.sum(arr))

6


##  minimum :

In [69]:
print(np.min(arr))

1


## max

In [70]:
print(np.max(arr))

3


## Pratice

In [74]:
#replace all negative in an array with 0
arr = np.array([3,-1,5,-2,7])
print(np.where(arr<0,0, arr))

[3 0 5 0 7]


In [77]:
# or
arr[arr<0] = 0
arr

array([3, 0, 5, 0, 7])

In [81]:
# extract all even numbers from an array
arr = np.array([1,2,3,4,5,6,7,8])
even_no = arr[arr%2 == 0]
print(even_no)

[2 4 6 8]


In [85]:
# or 
indices = np.where(arr%2 == 0)
print(indices)
print(arr[indices])

(array([1, 3, 5, 7]),)
[2 4 6 8]


In [98]:
# Reverse each row of 2D array
arr = np.array([
    [1,2,3],
    [4,5,6]])
b= arr[: ,::-1 ]
b

array([[3, 2, 1],
       [6, 5, 4]])

In [103]:
result = np.flip(arr,axis=1)
result

array([[3, 2, 1],
       [6, 5, 4]])

In [126]:
# count how many values fall inside a range
arr = np.array([10,22,35,50,70])
count = np.sum((arr>20) & (arr<60))

print(count)


3


In [127]:
# normalise an array(min-max scaling)
# new value =   (value - min_value)/(value-max - minvalue)

In [142]:
arr = np.array([10,20,30,40,50])
norm = (arr - np.min(arr)) / (np.max(arr) - np.min(arr))
norm

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [143]:
# Euclidian distance

In [157]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.sqrt(np.sum((a-b)**2))

np.float64(5.196152422706632)